### ISSUE TITLE
installation configuration instructions

### ISSUE THREAD

**Issue by msftcangoblowm** [nightfullstar/willyoumarryme_bot_telegram#1]
#### What's the problem this feature will solve?

The script looks great

For those not familiar with setting up Telegram bots, there are no setup instructions.

A step by step, regardless if it's completely obvious, would be very helpful.

With just the script, although your girl won the lottery, afraid other ladies hopes and dreams will remain just that, a dream.

#### Describe the solution you'd like

Detail in the README a step by step to setup the Telegram bot and show the bot in action. For the later, recommend [VHS tape](https://github.com/charmbracelet/vhs).

An explanation a six year old could follow to setup and install this TG bot.

#### Alternative Solutions

Leave the ladies in their current unmarried state forever. Their Tiktok and Instagram followers jealously will be kept at bay, but at the expense of society having less families.

**Comment by nightfullstar** [comment]
[https://github.com/nightfullstar/willyoumarryme_bot_telegram/commit/8d1c619747ae46480b7bf10913d77ef1321f42dd](url)  Added specific instructions.
